<?php
/**
 * @file
 * campus_demo_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function campus_demo_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => '1',
  'title' => 'Go trips Sunday',
  'log' => '',
  'status' => '1',
  'comment' => '2',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '93a39f77-a42c-67c4-2940-a4ff83ec4f4e',
  'type' => 'event',
  'language' => 'und',
  'created' => '1352087640',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '0aed5927-56d4-bc94-a508-ea9343b09faa',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Go trips Sunday - 18 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol>
	<li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose. &nbsp;&nbsp;&nbsp;&nbsp;We are committed to bringing people into a relationship with Jesus Christ. We are committed to &nbsp;creating a city-wide family church in which all are welcome and can get connected</li>
	<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a &nbsp;Church whose people are unified, prayerful and full of God&#39;s Spirit.</li>
	<li>
		&nbsp;<strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
	<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to &nbsp;reach out and minister to &nbsp;the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
	<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
	<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Go trips Sunday - 18 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol><li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose.     We are committed to bringing people into a relationship with Jesus Christ. We are committed to  creating a city-wide family church in which all are welcome and can get connected</li>
<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a  Church whose people are unified, prayerful and full of God\'s Spirit.</li>
<li>
		 <strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to  reach out and minister to  the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_event_video' => array(
    'und' => array(
      0 => array(
        'fid' => '87',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_event_image' => array(
    'und' => array(
      0 => array(
        'fid' => '117',
        'alt' => '',
        'title' => '',
        'width' => '531',
        'height' => '630',
        'uid' => '1',
        'filename' => 'Screen-Shot-2012-09-21-at-12.21.png',
        'uri' => 'public://image/event/Screen-Shot-2012-09-21-at-12.21_0.png',
        'filemime' => 'image/png',
        'filesize' => '468756',
        'status' => '1',
        'timestamp' => '1352431530',
        'type' => 'image',
        'uuid' => 'e4459f45-606f-fe74-cd5f-201f720285ec',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_is_global' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_upcoming_event' => array(),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2012-11-18 03:45:00',
        'timezone' => 'Asia/Ho_Chi_Minh',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
        'db' => array(
          'value' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-18T03:45:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-18T03:45:00+00:00',
            'date' => '2012-11-18 03:45:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
          'value2' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-18T03:45:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-18T03:45:00+00:00',
            'date' => '2012-11-18 03:45:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
        ),
      ),
    ),
  ),
  'field_upcoming_image' => array(),
  'field_event_type' => array(
    'und' => array(
      0 => array(
        'tid' => '5',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-05 10:54:00 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Ministry Connect Form',
  'log' => '',
  'status' => '1',
  'comment' => '2',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '66b4d678-c388-c064-01d3-f296ae163ec7',
  'type' => 'webform',
  'language' => 'und',
  'created' => '1352023993',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '0f19609a-e2c4-3794-d994-861c22c2f900',
  'revision_uid' => '1',
  'body' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'webform' => array(
    'nid' => '4',
    'confirmation' => '',
    'confirmation_format' => 'filtered_html',
    'redirect_url' => '<confirmation>',
    'status' => '1',
    'block' => '1',
    'teaser' => '0',
    'allow_draft' => '0',
    'auto_save' => '0',
    'submit_notice' => '1',
    'submit_text' => 'Submit',
    'submit_limit' => '-1',
    'submit_interval' => '-1',
    'total_submit_limit' => '-1',
    'total_submit_interval' => '-1',
    'record_exists' => TRUE,
    'roles' => array(
      0 => '1',
      1 => '2',
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 4,
        'cid' => '1',
        'pid' => '0',
        'form_key' => 'full_name',
        'name' => 'Full name',
        'type' => 'textfield',
        'value' => 'Full name',
        'extra' => array(
          'title_display' => 'inline',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '0',
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 4,
        'cid' => '2',
        'pid' => '0',
        'form_key' => 'contact_number',
        'name' => 'Contact number',
        'type' => 'textfield',
        'value' => 'Contact number',
        'extra' => array(
          'title_display' => 'inline',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '1',
        'page_num' => 1,
      ),
      3 => array(
        'nid' => 4,
        'cid' => '3',
        'pid' => '0',
        'form_key' => 'email',
        'name' => 'Email',
        'type' => 'email',
        'value' => 'Email',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 1,
          'conditional_operator' => '=',
          'width' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '2',
        'page_num' => 1,
      ),
      4 => array(
        'nid' => 4,
        'cid' => '4',
        'pid' => '0',
        'form_key' => 'nid',
        'name' => 'Nid',
        'type' => 'hidden',
        'value' => '',
        'extra' => array(
          'hidden_type' => 'hidden',
          'conditional_operator' => '=',
          'private' => 0,
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '3',
        'page_num' => 1,
      ),
    ),
  ),
  'machine_name' => 'ministry_connect_form',
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-04 17:13:13 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Concierge Form',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'dc720395-3066-7424-61d4-22c3870a1cbd',
  'type' => 'webform',
  'language' => 'und',
  'created' => '1352344060',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '14536b6f-853e-7904-0112-5d25a822b988',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>&nbsp;</p>
<p>
	<script type="text/javascript">
var dd = new YAHOO.util.DD(\'maindiv\'); dd.setHandleElId(\'titlediv\');	</script>
	<script type="text/javascript">
var dd = new YAHOO.util.DD(\'maindiv\'); dd.setHandleElId(\'titlediv\');	</script>
</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p> </p>
<p><script type="text/javascript">
<!--//--><![CDATA[// ><!--

var dd = new YAHOO.util.DD(\'maindiv\'); dd.setHandleElId(\'titlediv\');	
//--><!]]>
</script><script type="text/javascript">
<!--//--><![CDATA[// ><!--

var dd = new YAHOO.util.DD(\'maindiv\'); dd.setHandleElId(\'titlediv\');	
//--><!]]>
</script></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'webform' => array(
    'nid' => '24',
    'confirmation' => '',
    'confirmation_format' => 'filtered_html',
    'redirect_url' => '<confirmation>',
    'status' => '1',
    'block' => '0',
    'teaser' => '0',
    'allow_draft' => '0',
    'auto_save' => '0',
    'submit_notice' => '1',
    'submit_text' => 'Reserve a seat',
    'submit_limit' => '-1',
    'submit_interval' => '-1',
    'total_submit_limit' => '-1',
    'total_submit_interval' => '-1',
    'record_exists' => TRUE,
    'roles' => array(
      0 => '1',
      1 => '2',
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 24,
        'cid' => '1',
        'pid' => '0',
        'form_key' => 'name',
        'name' => 'Name',
        'type' => 'textfield',
        'value' => '',
        'extra' => array(
          'title_display' => 'inline',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '0',
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 24,
        'cid' => '2',
        'pid' => '0',
        'form_key' => 'number',
        'name' => 'Number',
        'type' => 'number',
        'value' => '',
        'extra' => array(
          'title_display' => 'inline',
          'private' => 0,
          'type' => 'textfield',
          'decimals' => '',
          'separator' => ',',
          'point' => '.',
          'unique' => 0,
          'integer' => 1,
          'conditional_operator' => '=',
          'excludezero' => 0,
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'min' => '',
          'max' => '',
          'step' => '',
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '1',
        'page_num' => 1,
      ),
      3 => array(
        'nid' => 24,
        'cid' => '3',
        'pid' => '0',
        'form_key' => 'email',
        'name' => 'Email',
        'type' => 'email',
        'value' => '',
        'extra' => array(
          'title_display' => 'inline',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '2',
        'page_num' => 1,
      ),
      4 => array(
        'nid' => 24,
        'cid' => '4',
        'pid' => '0',
        'form_key' => 'services',
        'name' => 'Services',
        'type' => 'select',
        'value' => '1',
        'extra' => array(
          'items' => '1|9 AM
2|11 AM
3|5 PM',
          'multiple' => 0,
          'title_display' => 'inline',
          'private' => 0,
          'aslist' => 0,
          'optrand' => 0,
          'conditional_operator' => '=',
          'other_option' => NULL,
          'other_text' => 'Other...',
          'description' => '',
          'custom_keys' => FALSE,
          'options_source' => '',
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '3',
        'page_num' => 1,
      ),
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 10:07:40 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'iConnect Groups',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '9c50275c-c19a-cd44-095d-645cddaf0737',
  'type' => 'ministry',
  'language' => 'und',
  'created' => '1351848060',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '1872bc64-d1a6-eb44-f9f9-6c331f352157',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>iConnect Groups are the life-blood of Paradise Community Church! Something amazing happens when we get together in a small group of people and share the goodness of God with one another. It&rsquo;s in small groups we can &ldquo;be ourselves&rdquo; and build trust, relationship and community, as well as develop our gifts and talents. At Paradise Community Church, we call them &ldquo;iConnect Groups&rdquo;, because we believe they are essential to a healthy life in God. If you work during the day, we have night iCoonect Groups across Adelaide, while if you&rsquo;re home during the day, Day iConnect Groups are a great way to get out of the house and spend time with others. If you&rsquo;re not part of an iConnect Group, see the iConnect Group listing for one nearest you and find out what you&rsquo;re missing!</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>iConnect Groups are the life-blood of Paradise Community Church! Something amazing happens when we get together in a small group of people and share the goodness of God with one another. It’s in small groups we can “be ourselves” and build trust, relationship and community, as well as develop our gifts and talents. At Paradise Community Church, we call them “iConnect Groups”, because we believe they are essential to a healthy life in God. If you work during the day, we have night iCoonect Groups across Adelaide, while if you’re home during the day, Day iConnect Groups are a great way to get out of the house and spend time with others. If you’re not part of an iConnect Group, see the iConnect Group listing for one nearest you and find out what you’re missing!</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_email' => array(),
  'field_custom_teaser_image' => array(
    'und' => array(
      0 => array(
        'fid' => '60',
        'alt' => '',
        'title' => '',
        'width' => '381',
        'height' => '315',
        'uid' => '1',
        'filename' => 'connect.jpg',
        'uri' => 'public://image/middle_image/connect.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '18932',
        'status' => '1',
        'timestamp' => '1352362738',
        'type' => 'image',
        'uuid' => '87902968-e3f8-aca4-6d70-869770c6c838',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_video' => array(
    'und' => array(
      0 => array(
        'fid' => '85',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-02 16:21:00 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Homepage video',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'ef9f011a-a274-b314-19c1-3eab5e7700f2',
  'type' => 'video',
  'language' => 'und',
  'created' => '1352425056',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '1f3908e2-38a3-5674-ed89-d65149f5199d',
  'revision_uid' => '1',
  'body' => array(),
  'field_video' => array(
    'und' => array(
      0 => array(
        'fid' => '75',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_is_home' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-09 08:37:36 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Internship',
  'log' => '',
  'status' => '1',
  'comment' => '2',
  'promote' => '1',
  'sticky' => '0',
  'vuuid' => 'e8e16db1-f147-0b84-d995-e3b4509e32ec',
  'type' => 'webform',
  'language' => 'und',
  'created' => '1352359577',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '1f5147ca-e2e5-e704-dd5c-f05c52ec82d0',
  'revision_uid' => '1',
  'body' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'webform' => array(
    'nid' => '31',
    'confirmation' => '',
    'confirmation_format' => 'filtered_html',
    'redirect_url' => '<confirmation>',
    'status' => '1',
    'block' => '1',
    'teaser' => '0',
    'allow_draft' => '0',
    'auto_save' => '0',
    'submit_notice' => '1',
    'submit_text' => 'Grow',
    'submit_limit' => '-1',
    'submit_interval' => '-1',
    'total_submit_limit' => '-1',
    'total_submit_interval' => '-1',
    'record_exists' => TRUE,
    'roles' => array(
      0 => '1',
      1 => '2',
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 31,
        'cid' => '1',
        'pid' => '0',
        'form_key' => 'email',
        'name' => 'Email',
        'type' => 'email',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '0',
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 31,
        'cid' => '2',
        'pid' => '0',
        'form_key' => 'nid',
        'name' => 'Nid',
        'type' => 'hidden',
        'value' => '',
        'extra' => array(
          'hidden_type' => 'hidden',
          'conditional_operator' => '=',
          'private' => 0,
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '1',
        'page_num' => 1,
      ),
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 14:26:17 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Baptism on Sunday!',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '5c978525-b7c3-8794-45b9-85526f03684d',
  'type' => 'event',
  'language' => 'und',
  'created' => '1352087935',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '351cae84-5074-4034-2ddc-521ed50f485b',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>New to influencers dinner - 18 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol>
	<li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose. &nbsp;&nbsp;&nbsp;&nbsp;We are committed to bringing people into a relationship with Jesus Christ. We are committed to &nbsp;creating a city-wide family church in which all are welcome and can get connected</li>
	<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a &nbsp;Church whose people are unified, prayerful and full of God&#39;s Spirit.</li>
	<li>
		&nbsp;<strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
	<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to &nbsp;reach out and minister to &nbsp;the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
	<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
	<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>New to influencers dinner - 18 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol><li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose.     We are committed to bringing people into a relationship with Jesus Christ. We are committed to  creating a city-wide family church in which all are welcome and can get connected</li>
<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a  Church whose people are unified, prayerful and full of God\'s Spirit.</li>
<li>
		 <strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to  reach out and minister to  the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_event_video' => array(
    'und' => array(
      0 => array(
        'fid' => '81',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_event_image' => array(
    'und' => array(
      0 => array(
        'fid' => '120',
        'alt' => '',
        'title' => '',
        'width' => '531',
        'height' => '630',
        'uid' => '1',
        'filename' => 'Screen-Shot-2012-09-21-at-12.21.png',
        'uri' => 'public://image/event/Screen-Shot-2012-09-21-at-12.21_1.png',
        'filemime' => 'image/png',
        'filesize' => '468756',
        'status' => '1',
        'timestamp' => '1352431595',
        'type' => 'image',
        'uuid' => 'cfb299a3-c15a-8e84-ad4c-6f024c54225d',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_is_global' => array(),
  'field_upcoming_event' => array(),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2012-11-18 10:00:00',
        'timezone' => 'Asia/Ho_Chi_Minh',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
        'db' => array(
          'value' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-18T10:00:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-18T10:00:00+00:00',
            'date' => '2012-11-18 10:00:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
          'value2' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-18T10:00:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-18T10:00:00+00:00',
            'date' => '2012-11-18 10:00:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
        ),
      ),
    ),
  ),
  'field_upcoming_image' => array(),
  'field_event_type' => array(
    'und' => array(
      0 => array(
        'tid' => '6',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-05 10:58:55 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Womens morning tea',
  'log' => '',
  'status' => '1',
  'comment' => '2',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '0d3c6fc8-6288-5474-5597-837640153239',
  'type' => 'event',
  'language' => 'und',
  'created' => '1352088050',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '3947458a-b281-d8d4-ada0-48c15040ec67',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Womens morning tea - 24 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol>
	<li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose. &nbsp;&nbsp;&nbsp;&nbsp;We are committed to bringing people into a relationship with Jesus Christ. We are committed to &nbsp;creating a city-wide family church in which all are welcome and can get connected</li>
	<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a &nbsp;Church whose people are unified, prayerful and full of God&#39;s Spirit.</li>
	<li>
		&nbsp;<strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
	<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to &nbsp;reach out and minister to &nbsp;the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
	<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
	<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Womens morning tea - 24 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol><li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose.     We are committed to bringing people into a relationship with Jesus Christ. We are committed to  creating a city-wide family church in which all are welcome and can get connected</li>
<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a  Church whose people are unified, prayerful and full of God\'s Spirit.</li>
<li>
		 <strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to  reach out and minister to  the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_event_video' => array(
    'und' => array(
      0 => array(
        'fid' => '83',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_event_image' => array(
    'und' => array(
      0 => array(
        'fid' => '118',
        'alt' => '',
        'title' => '',
        'width' => '525',
        'height' => '306',
        'uid' => '1',
        'filename' => 'Screen-Shot-2012-08-06-at-10.43.png',
        'uri' => 'public://image/event/Screen-Shot-2012-08-06-at-10.43_1.png',
        'filemime' => 'image/png',
        'filesize' => '280165',
        'status' => '1',
        'timestamp' => '1352431592',
        'type' => 'image',
        'uuid' => 'd6ced390-0ebf-ee04-e16e-2269e30bd9d0',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_is_global' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_upcoming_event' => array(),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2012-11-24 02:00:00',
        'timezone' => 'Asia/Ho_Chi_Minh',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
        'db' => array(
          'value' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-24T02:00:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-24T02:00:00+00:00',
            'date' => '2012-11-24 02:00:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
          'value2' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-24T02:00:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-24T02:00:00+00:00',
            'date' => '2012-11-24 02:00:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
        ),
      ),
    ),
  ),
  'field_upcoming_image' => array(),
  'field_event_type' => array(
    'und' => array(
      0 => array(
        'tid' => '5',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-05 11:00:50 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Prayer & Fasting',
  'log' => '',
  'status' => '1',
  'comment' => '2',
  'promote' => '1',
  'sticky' => '0',
  'vuuid' => 'bac4b7df-fc75-b0d4-a901-7afdbfc0ad4d',
  'type' => 'webform',
  'language' => 'und',
  'created' => '1352359455',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '4755c7e1-1f4d-75a4-a1bd-8576a0a7d260',
  'revision_uid' => '1',
  'body' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'webform' => array(
    'nid' => '28',
    'confirmation' => '',
    'confirmation_format' => 'filtered_html',
    'redirect_url' => '<confirmation>',
    'status' => '1',
    'block' => '1',
    'teaser' => '0',
    'allow_draft' => '0',
    'auto_save' => '0',
    'submit_notice' => '1',
    'submit_text' => 'Commit',
    'submit_limit' => '-1',
    'submit_interval' => '-1',
    'total_submit_limit' => '-1',
    'total_submit_interval' => '-1',
    'record_exists' => TRUE,
    'roles' => array(
      0 => '1',
      1 => '2',
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 28,
        'cid' => '1',
        'pid' => '0',
        'form_key' => 'email',
        'name' => 'Email',
        'type' => 'email',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '0',
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 28,
        'cid' => '2',
        'pid' => '0',
        'form_key' => 'nid',
        'name' => 'Nid',
        'type' => 'hidden',
        'value' => '',
        'extra' => array(
          'hidden_type' => 'hidden',
          'conditional_operator' => '=',
          'private' => 0,
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '1',
        'page_num' => 1,
      ),
    ),
  ),
  'machine_name' => 'prayer_fasting',
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 14:24:15 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Internship',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '447cc811-0fbb-c054-010b-44728a379728',
  'type' => 'college',
  'language' => 'und',
  'created' => '1352367209',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '607b8628-9448-6c94-f92f-71099ed6999b',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Vestibulum id ligula porta felis euismod semper. Curabitur blandit tempus porttitor. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Aenean eu leo quam...</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Vestibulum id ligula porta felis euismod semper. Curabitur blandit tempus porttitor. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Aenean eu leo quam...</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_custom_teaser_image' => array(
    'und' => array(
      0 => array(
        'fid' => '67',
        'alt' => '',
        'title' => '',
        'width' => '248',
        'height' => '258',
        'uid' => '1',
        'filename' => 'influencer_03.png',
        'uri' => 'public://influencer_03_2.png',
        'filemime' => 'image/png',
        'filesize' => '70927',
        'status' => '1',
        'timestamp' => '1352367209',
        'type' => 'image',
        'uuid' => '28f321fe-a7d7-0234-217c-b76ab97fdb5f',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_link_text' => array(
    'und' => array(
      0 => array(
        'value' => 'Grow',
        'format' => NULL,
        'safe_value' => 'Grow',
      ),
    ),
  ),
  'field_video' => array(
    'und' => array(
      0 => array(
        'fid' => '125',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 16:33:29 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Dan Lian',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '79eafd45-5abe-3184-7111-e95b7b28fc34',
  'type' => 'event',
  'language' => 'und',
  'created' => '1352087430',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '688b3330-510b-bf34-c98f-c53cd848335e',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Dan Lian - 16 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol>
	<li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose. &nbsp;&nbsp;&nbsp;&nbsp;We are committed to bringing people into a relationship with Jesus Christ. We are committed to &nbsp;creating a city-wide family church in which all are welcome and can get connected</li>
	<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a &nbsp;Church whose people are unified, prayerful and full of God&#39;s Spirit.</li>
	<li>
		&nbsp;<strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
	<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to &nbsp;reach out and minister to &nbsp;the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
	<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
	<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Dan Lian - 16 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol><li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose.     We are committed to bringing people into a relationship with Jesus Christ. We are committed to  creating a city-wide family church in which all are welcome and can get connected</li>
<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a  Church whose people are unified, prayerful and full of God\'s Spirit.</li>
<li>
		 <strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to  reach out and minister to  the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_event_video' => array(
    'und' => array(
      0 => array(
        'fid' => '93',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_event_image' => array(
    'und' => array(
      0 => array(
        'fid' => '121',
        'alt' => '',
        'title' => '',
        'width' => '878',
        'height' => '616',
        'uid' => '1',
        'filename' => 'Screen-Shot-2012-08-06-at-10.42.png',
        'uri' => 'public://image/event/Screen-Shot-2012-08-06-at-10.42_1.png',
        'filemime' => 'image/png',
        'filesize' => '896601',
        'status' => '1',
        'timestamp' => '1352431715',
        'type' => 'image',
        'uuid' => '9ee83706-56bc-bb04-5935-d44ab9df4340',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_is_global' => array(),
  'field_upcoming_event' => array(),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2012-11-16 03:30:00',
        'timezone' => 'Asia/Ho_Chi_Minh',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
        'db' => array(
          'value' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-16T03:30:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-16T03:30:00+00:00',
            'date' => '2012-11-16 03:30:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
          'value2' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-16T03:30:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-16T03:30:00+00:00',
            'date' => '2012-11-16 03:30:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
        ),
      ),
    ),
  ),
  'field_upcoming_image' => array(),
  'field_event_type' => array(
    'und' => array(
      0 => array(
        'tid' => '6',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-05 10:50:30 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Giving time',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'fdd65057-5f7c-4f64-7510-763bd8c04b82',
  'type' => 'webform',
  'language' => 'und',
  'created' => '1352344442',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '7c20a7c4-d20f-97f4-411a-a0bf220cc57c',
  'revision_uid' => '1',
  'body' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'webform' => array(
    'nid' => '25',
    'confirmation' => '',
    'confirmation_format' => 'filtered_html',
    'redirect_url' => '<confirmation>',
    'status' => '1',
    'block' => '1',
    'teaser' => '0',
    'allow_draft' => '0',
    'auto_save' => '0',
    'submit_notice' => '1',
    'submit_text' => 'Give',
    'submit_limit' => '-1',
    'submit_interval' => '-1',
    'total_submit_limit' => '-1',
    'total_submit_interval' => '-1',
    'record_exists' => TRUE,
    'roles' => array(
      0 => '1',
      1 => '2',
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 25,
        'cid' => '1',
        'pid' => '0',
        'form_key' => 'first_name',
        'name' => 'First name',
        'type' => 'textfield',
        'value' => '',
        'extra' => array(
          'title_display' => 'inline',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '0',
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 25,
        'cid' => '2',
        'pid' => '0',
        'form_key' => 'last_name',
        'name' => 'Last name',
        'type' => 'textfield',
        'value' => '',
        'extra' => array(
          'title_display' => 'inline',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '1',
        'page_num' => 1,
      ),
      4 => array(
        'nid' => 25,
        'cid' => '4',
        'pid' => '0',
        'form_key' => 'email',
        'name' => 'Email',
        'type' => 'email',
        'value' => '',
        'extra' => array(
          'title_display' => 'inline',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '3',
        'page_num' => 1,
      ),
      5 => array(
        'nid' => 25,
        'cid' => '5',
        'pid' => '0',
        'form_key' => 'skills',
        'name' => 'Skills',
        'type' => 'textarea',
        'value' => '',
        'extra' => array(
          'title_display' => 0,
          'private' => 0,
          'resizable' => 1,
          'disabled' => 0,
          'conditional_operator' => '=',
          'cols' => '',
          'rows' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '4',
        'page_num' => 1,
      ),
      6 => array(
        'nid' => 25,
        'cid' => '6',
        'pid' => '0',
        'form_key' => 'phone',
        'name' => 'Phone',
        'type' => 'textfield',
        'value' => 'Phone',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'maxlength' => '20',
          'conditional_operator' => '=',
          'width' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '5',
        'page_num' => 1,
      ),
    ),
  ),
  'machine_name' => 'giving_time',
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 10:14:02 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'New to influencers night',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '929913ee-59db-4a04-79ed-3000e97d6f89',
  'type' => 'event',
  'language' => 'und',
  'created' => '1352185319',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '80034c9c-3e90-f324-3978-fb4d01ee137f',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>New to influencers night - 26 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol>
	<li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose. &nbsp;&nbsp;&nbsp;&nbsp;We are committed to bringing people into a relationship with Jesus Christ. We are committed to &nbsp;creating a city-wide family church in which all are welcome and can get connected</li>
	<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a &nbsp;Church whose people are unified, prayerful and full of God&#39;s Spirit.</li>
	<li>
		&nbsp;<strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
	<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to &nbsp;reach out and minister to &nbsp;the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
	<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
	<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>New to influencers night - 26 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol><li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose.     We are committed to bringing people into a relationship with Jesus Christ. We are committed to  creating a city-wide family church in which all are welcome and can get connected</li>
<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a  Church whose people are unified, prayerful and full of God\'s Spirit.</li>
<li>
		 <strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to  reach out and minister to  the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_event_video' => array(
    'und' => array(
      0 => array(
        'fid' => '85',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_event_image' => array(
    'und' => array(
      0 => array(
        'fid' => '114',
        'alt' => '',
        'title' => '',
        'width' => '525',
        'height' => '306',
        'uid' => '1',
        'filename' => 'Screen-Shot-2012-08-06-at-10.43.png',
        'uri' => 'public://image/event/Screen-Shot-2012-08-06-at-10.43.png',
        'filemime' => 'image/png',
        'filesize' => '280165',
        'status' => '1',
        'timestamp' => '1352431498',
        'type' => 'image',
        'uuid' => '20d02b3c-a176-5524-e905-43b5538c5c29',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_is_global' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_upcoming_event' => array(),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2012-11-26 07:00:00',
        'timezone' => 'Asia/Ho_Chi_Minh',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
        'db' => array(
          'value' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-26T07:00:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-26T07:00:00+00:00',
            'date' => '2012-11-26 07:00:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
          'value2' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-26T07:00:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-26T07:00:00+00:00',
            'date' => '2012-11-26 07:00:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
        ),
      ),
    ),
  ),
  'field_upcoming_image' => array(),
  'field_event_type' => array(
    'und' => array(
      0 => array(
        'tid' => '5',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-06 14:01:59 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'International Ministries',
  'log' => '',
  'status' => '1',
  'comment' => '2',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '3ca9ebcd-09ea-06b4-3d40-942b354b1202',
  'type' => 'ministry',
  'language' => 'und',
  'created' => '1351847801',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '8bf4ac99-32ad-1614-4dae-b476736b2708',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Paradise International Ministries is for people of African or Asian origin and for International Students studying Adelaide.&nbsp; We aim to provide a Christian environment to migrant families and visiting students to grow spiritually and develop wholesome relationships within the Christian community.&nbsp; We encourage people to be involved in the life of the Church through the expression of their gifts and talents &ndash; our African and Asian believers are a vibrant and highly valued part of our congregation.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Paradise International Ministries is for people of African or Asian origin and for International Students studying Adelaide.  We aim to provide a Christian environment to migrant families and visiting students to grow spiritually and develop wholesome relationships within the Christian community.  We encourage people to be involved in the life of the Church through the expression of their gifts and talents – our African and Asian believers are a vibrant and highly valued part of our congregation.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_email' => array(),
  'field_custom_teaser_image' => array(
    'und' => array(
      0 => array(
        'fid' => '59',
        'alt' => '',
        'title' => '',
        'width' => '300',
        'height' => '300',
        'uid' => '1',
        'filename' => 'icf_logo.gif',
        'uri' => 'public://image/middle_image/icf_logo.gif',
        'filemime' => 'image/gif',
        'filesize' => '25822',
        'status' => '1',
        'timestamp' => '1352362729',
        'type' => 'image',
        'uuid' => 'b529f88d-e6da-bcf4-7185-19670b2afd01',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_video' => array(
    'und' => array(
      0 => array(
        'fid' => '93',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-02 16:16:41 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Baby Dedications',
  'log' => '',
  'status' => '1',
  'comment' => '2',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '25002f6a-710f-4a94-2113-c0ee16414e1a',
  'type' => 'event',
  'language' => 'und',
  'created' => '1352086354',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '9ef15dc1-5037-9bc4-a1cf-22fb3d607fae',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Baby Dedications - 11 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol>
	<li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose. &nbsp;&nbsp;&nbsp;&nbsp;We are committed to bringing people into a relationship with Jesus Christ. We are committed to &nbsp;creating a city-wide family church in which all are welcome and can get connected</li>
	<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a &nbsp;Church whose people are unified, prayerful and full of God&#39;s Spirit.</li>
	<li>
		&nbsp;<strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
	<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to &nbsp;reach out and minister to &nbsp;the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
	<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
	<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Baby Dedications - 11 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol><li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose.     We are committed to bringing people into a relationship with Jesus Christ. We are committed to  creating a city-wide family church in which all are welcome and can get connected</li>
<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a  Church whose people are unified, prayerful and full of God\'s Spirit.</li>
<li>
		 <strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to  reach out and minister to  the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_event_video' => array(
    'und' => array(
      0 => array(
        'fid' => '89',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_event_image' => array(
    'und' => array(
      0 => array(
        'fid' => '115',
        'alt' => '',
        'title' => '',
        'width' => '525',
        'height' => '306',
        'uid' => '1',
        'filename' => 'Screen-Shot-2012-08-06-at-10.43.png',
        'uri' => 'public://image/event/Screen-Shot-2012-08-06-at-10.43_0.png',
        'filemime' => 'image/png',
        'filesize' => '280165',
        'status' => '1',
        'timestamp' => '1352431519',
        'type' => 'image',
        'uuid' => '97029b18-4895-6234-6598-07d80087a786',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_is_global' => array(),
  'field_upcoming_event' => array(),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2012-11-11 03:30:00',
        'timezone' => 'Asia/Ho_Chi_Minh',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
        'db' => array(
          'value' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-11T03:30:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-11T03:30:00+00:00',
            'date' => '2012-11-11 03:30:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
          'value2' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-11T03:30:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-11T03:30:00+00:00',
            'date' => '2012-11-11 03:30:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
        ),
      ),
    ),
  ),
  'field_upcoming_image' => array(),
  'field_event_type' => array(
    'und' => array(
      0 => array(
        'tid' => '6',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-05 10:32:34 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Bring',
  'log' => '',
  'status' => '0',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '0da9cb4d-4680-ca84-1978-7ecde45da243',
  'type' => 'college',
  'language' => 'und',
  'created' => '1352367206',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'a196238c-e610-8f44-4df1-d69ed5144c2f',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Vestibulum id ligula porta felis euismod semper. Curabitur blandit tempus porttitor. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Aenean eu leo quam...</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Vestibulum id ligula porta felis euismod semper. Curabitur blandit tempus porttitor. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Aenean eu leo quam...</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_custom_teaser_image' => array(
    'und' => array(
      0 => array(
        'fid' => '66',
        'alt' => '',
        'title' => '',
        'width' => '248',
        'height' => '258',
        'uid' => '1',
        'filename' => 'influencer_03.png',
        'uri' => 'public://influencer_03_1.png',
        'filemime' => 'image/png',
        'filesize' => '70927',
        'status' => '1',
        'timestamp' => '1352367206',
        'type' => 'image',
        'uuid' => '43b9e6b1-30af-c2a4-29d9-8a78362862ac',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_link_text' => array(
    'und' => array(
      0 => array(
        'value' => 'Bring',
        'format' => NULL,
        'safe_value' => 'Bring',
      ),
    ),
  ),
  'field_video' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 16:33:26 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Give',
  'log' => '',
  'status' => '1',
  'comment' => '2',
  'promote' => '1',
  'sticky' => '0',
  'vuuid' => '5bf14f7a-695f-4ba4-4d7a-304a543e6da4',
  'type' => 'webform',
  'language' => 'und',
  'created' => '1352359502',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'a1b88651-9a50-d664-912a-380a540c6c53',
  'revision_uid' => '1',
  'body' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'webform' => array(
    'nid' => '29',
    'confirmation' => '',
    'confirmation_format' => 'filtered_html',
    'redirect_url' => '<confirmation>',
    'status' => '1',
    'block' => '1',
    'teaser' => '0',
    'allow_draft' => '0',
    'auto_save' => '0',
    'submit_notice' => '1',
    'submit_text' => 'Give',
    'submit_limit' => '-1',
    'submit_interval' => '-1',
    'total_submit_limit' => '-1',
    'total_submit_interval' => '-1',
    'record_exists' => TRUE,
    'roles' => array(
      0 => '1',
      1 => '2',
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 29,
        'cid' => '1',
        'pid' => '0',
        'form_key' => 'email',
        'name' => 'Email',
        'type' => 'email',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '0',
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 29,
        'cid' => '2',
        'pid' => '0',
        'form_key' => 'nid',
        'name' => 'Nid',
        'type' => 'hidden',
        'value' => '',
        'extra' => array(
          'hidden_type' => 'hidden',
          'conditional_operator' => '=',
          'private' => 0,
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '1',
        'page_num' => 1,
      ),
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 14:25:02 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Ashley Evans Event',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '5c64a90f-59b1-4344-0d62-dfdf2b872c60',
  'type' => 'event',
  'language' => 'und',
  'created' => '1352086129',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'a3303c48-fb1c-c734-4db2-42edc7dc319b',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Ashley Evans Event - 09 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol>
	<li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose. &nbsp;&nbsp;&nbsp;&nbsp;We are committed to bringing people into a relationship with Jesus Christ. We are committed to &nbsp;creating a city-wide family church in which all are welcome and can get connected</li>
	<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a &nbsp;Church whose people are unified, prayerful and full of God&#39;s Spirit.</li>
	<li>
		&nbsp;<strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
	<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to &nbsp;reach out and minister to &nbsp;the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
	<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
	<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Ashley Evans Event - 09 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol><li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose.     We are committed to bringing people into a relationship with Jesus Christ. We are committed to  creating a city-wide family church in which all are welcome and can get connected</li>
<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a  Church whose people are unified, prayerful and full of God\'s Spirit.</li>
<li>
		 <strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to  reach out and minister to  the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_event_video' => array(
    'und' => array(
      0 => array(
        'fid' => '79',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_event_image' => array(
    'und' => array(
      0 => array(
        'fid' => '119',
        'alt' => '',
        'title' => '',
        'width' => '878',
        'height' => '616',
        'uid' => '1',
        'filename' => 'Screen-Shot-2012-08-06-at-10.42.png',
        'uri' => 'public://image/event/Screen-Shot-2012-08-06-at-10.42_0.png',
        'filemime' => 'image/png',
        'filesize' => '896601',
        'status' => '1',
        'timestamp' => '1352431589',
        'type' => 'image',
        'uuid' => '42b38e50-26e0-3784-f97b-b2c69367806f',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_is_global' => array(),
  'field_upcoming_event' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2012-11-09 03:30:00',
        'timezone' => 'Asia/Ho_Chi_Minh',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
        'db' => array(
          'value' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-09T03:30:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-09T03:30:00+00:00',
            'date' => '2012-11-09 03:30:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
          'value2' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-09T03:30:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-09T03:30:00+00:00',
            'date' => '2012-11-09 03:30:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
        ),
      ),
    ),
  ),
  'field_upcoming_image' => array(
    'und' => array(
      0 => array(
        'fid' => '20',
        'alt' => 'Upcoming event ',
        'title' => 'Upcoming event ',
        'width' => '874',
        'height' => '606',
        'uid' => '1',
        'filename' => 'Screen-Shot-2012-08-06-at-10.20.png',
        'uri' => 'public://image/upcoming/Screen-Shot-2012-08-06-at-10.20.png',
        'filemime' => 'image/png',
        'filesize' => '1039250',
        'status' => '1',
        'timestamp' => '1352089593',
        'type' => 'image',
        'uuid' => '506b3cc2-3074-d064-217e-46bc5d5f147f',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_event_type' => array(
    'und' => array(
      0 => array(
        'tid' => '6',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-05 10:28:49 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Prayer & Fasting',
  'log' => '',
  'status' => '0',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '6b426bee-d26e-6bd4-6577-fe0ffd9d93a8',
  'type' => 'college',
  'language' => 'und',
  'created' => '1352360624',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'b6eef815-0e68-68d4-f913-4b224a78ed7d',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Paradise International Ministries is for people of African or Asian origin and for International Students studying Adelaide.&nbsp; We aim to provide a Christian environment to migrant families and visiting students to grow spiritually and develop wholesome relationships within the Christian community.&nbsp; We encourage people to be involved in the life of the Church through the expression of their gifts and talents &ndash; our African and Asian believers are a vibrant and highly valued part of our congregation.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Paradise International Ministries is for people of African or Asian origin and for International Students studying Adelaide.  We aim to provide a Christian environment to migrant families and visiting students to grow spiritually and develop wholesome relationships within the Christian community.  We encourage people to be involved in the life of the Church through the expression of their gifts and talents – our African and Asian believers are a vibrant and highly valued part of our congregation.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_custom_teaser_image' => array(
    'und' => array(
      0 => array(
        'fid' => '58',
        'alt' => '',
        'title' => '',
        'width' => '300',
        'height' => '200',
        'uid' => '1',
        'filename' => 'jaradandsarah.jpg',
        'uri' => 'public://jaradandsarah_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => '11021',
        'status' => '1',
        'timestamp' => '1352362102',
        'type' => 'image',
        'uuid' => 'f41166b6-014c-c6c4-e1b1-322ab89f8e3d',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_link_text' => array(
    'und' => array(
      0 => array(
        'value' => 'Commit',
        'format' => NULL,
        'safe_value' => 'Commit',
      ),
    ),
  ),
  'field_video' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 14:43:44 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Steve Kennedy',
  'log' => '',
  'status' => '1',
  'comment' => '2',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '3622005b-4e7f-b504-21c5-f9271dd927c4',
  'type' => 'event',
  'language' => 'und',
  'created' => '1352185200',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'c0f1a428-b292-0b64-adde-9d04d48cf3cc',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Steve Kennedy - 2 &amp; 23 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol>
	<li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose. &nbsp;&nbsp;&nbsp;&nbsp;We are committed to bringing people into a relationship with Jesus Christ. We are committed to &nbsp;creating a city-wide family church in which all are welcome and can get connected</li>
	<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a &nbsp;Church whose people are unified, prayerful and full of God&#39;s Spirit.</li>
	<li>
		&nbsp;<strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
	<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to &nbsp;reach out and minister to &nbsp;the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
	<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
	<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Steve Kennedy - 2 &amp; 23 Nov</p>
<p>Our core values reflect how we make decisions in order to fulfil our vision.</p>
<ol><li>
		<strong>Connecting People to God and Each Other</strong>:<br />
		We believe in the potential of one person and seeing them flourish in their God given purpose.     We are committed to bringing people into a relationship with Jesus Christ. We are committed to  creating a city-wide family church in which all are welcome and can get connected</li>
<li>
		<strong>Reliance on the Holy Spirit</strong><br />
		We are dependent on the Holy Spirit, we are a  Church whose people are unified, prayerful and full of God\'s Spirit.</li>
<li>
		 <strong>Authenticity</strong>: We believe in a church community that lives their everyday life with integrity, trustworthiness, enjoyment, wholeness and dependence on God</li>
<li>
		<strong>Service before self</strong>:<br />
		We accept, help and value people and will do whatever it takes to  reach out and minister to  the lost and broken and to connect people to God through a relationship with Jesus Christ</li>
<li>
		<strong>Excellence</strong>:<br />
		We serve with a spirit of excellence, with integrity and compassion for our community, our nation and our world. Excellence honours God and inspires people</li>
<li>
		<strong>Unity</strong>:<br />
		We believe that unity is the fabric which holds the diversity of who we are together. Unity has a message so clear that lives are changed forever and potential is fulfilled through the power of His Word.</li>
</ol>',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_event_video' => array(
    'und' => array(
      0 => array(
        'fid' => '91',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_event_image' => array(
    'und' => array(
      0 => array(
        'fid' => '112',
        'alt' => '',
        'title' => '',
        'width' => '878',
        'height' => '616',
        'uid' => '1',
        'filename' => 'Screen-Shot-2012-08-06-at-10.42.png',
        'uri' => 'public://image/event/Screen-Shot-2012-08-06-at-10.42.png',
        'filemime' => 'image/png',
        'filesize' => '896601',
        'status' => '1',
        'timestamp' => '1352431466',
        'type' => 'image',
        'uuid' => '4d068210-e7f1-1924-0d67-f037f8ea9704',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_is_global' => array(
    'und' => array(
      0 => array(
        'value' => '1',
      ),
    ),
  ),
  'field_upcoming_event' => array(),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2012-11-23 07:00:00',
        'timezone' => 'Asia/Ho_Chi_Minh',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
        'db' => array(
          'value' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-23T07:00:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-23T07:00:00+00:00',
            'date' => '2012-11-23 07:00:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
          'value2' => array(
            'granularity' => array(
              0 => 'year',
              1 => 'month',
              2 => 'day',
              3 => 'hour',
              4 => 'minute',
              5 => 'second',
              6 => 'timezone',
            ),
            'errors' => array(),
            '' . "\0" . 'DateObject' . "\0" . 'serializedTime' => '2012-11-23T07:00:00+00:00',
            '' . "\0" . 'DateObject' . "\0" . 'serializedTimezone' => 'UTC',
            'timeOnly' => FALSE,
            'dateOnly' => FALSE,
            'originalTime' => '2012-11-23T07:00:00+00:00',
            'date' => '2012-11-23 07:00:00',
            'timezone_type' => 3,
            'timezone' => 'UTC',
          ),
        ),
      ),
    ),
  ),
  'field_upcoming_image' => array(),
  'field_event_type' => array(
    'und' => array(
      0 => array(
        'tid' => '5',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-06 14:00:00 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Join Group',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '30943706-0259-1ad4-2179-4b895732488e',
  'type' => 'webform',
  'language' => 'und',
  'created' => '1352343702',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'ce7a84f2-d1b0-cf04-398a-1cac6ee9ccde',
  'revision_uid' => '1',
  'body' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'webform' => array(
    'nid' => '23',
    'confirmation' => '',
    'confirmation_format' => 'filtered_html',
    'redirect_url' => '<confirmation>',
    'status' => '1',
    'block' => '1',
    'teaser' => '0',
    'allow_draft' => '0',
    'auto_save' => '0',
    'submit_notice' => '1',
    'submit_text' => '',
    'submit_limit' => '-1',
    'submit_interval' => '-1',
    'total_submit_limit' => '-1',
    'total_submit_interval' => '-1',
    'record_exists' => TRUE,
    'roles' => array(
      0 => '1',
      1 => '2',
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 23,
        'cid' => '1',
        'pid' => '0',
        'form_key' => 'first_name',
        'name' => 'First name',
        'type' => 'textfield',
        'value' => 'First name',
        'extra' => array(
          'title_display' => 'inline',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '0',
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 23,
        'cid' => '2',
        'pid' => '0',
        'form_key' => 'last_name',
        'name' => 'Last name',
        'type' => 'textfield',
        'value' => 'Last name',
        'extra' => array(
          'title_display' => 'inline',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '1',
        'page_num' => 1,
      ),
      4 => array(
        'nid' => 23,
        'cid' => '4',
        'pid' => '0',
        'form_key' => 'email_address',
        'name' => 'Email address',
        'type' => 'email',
        'value' => 'Email address',
        'extra' => array(
          'title_display' => 'inline',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '2',
        'page_num' => 1,
      ),
      8 => array(
        'nid' => 23,
        'cid' => '8',
        'pid' => '0',
        'form_key' => 'phone_number',
        'name' => 'Phone number',
        'type' => 'textfield',
        'value' => 'Phone number',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'maxlength' => '20',
          'conditional_operator' => '=',
          'width' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '3',
        'page_num' => 1,
      ),
      7 => array(
        'nid' => 23,
        'cid' => '7',
        'pid' => '0',
        'form_key' => 'age',
        'name' => 'Age',
        'type' => 'textfield',
        'value' => 'Age',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'maxlength' => '3',
          'conditional_operator' => '=',
          'width' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '4',
        'page_num' => 1,
      ),
      9 => array(
        'nid' => 23,
        'cid' => '9',
        'pid' => '0',
        'form_key' => 'postcode',
        'name' => 'Postcode',
        'type' => 'textfield',
        'value' => 'Postcode/Zipcode',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'maxlength' => '30',
          'conditional_operator' => '=',
          'width' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '5',
        'page_num' => 1,
      ),
    ),
  ),
  'machine_name' => 'join_group',
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 10:01:42 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Go Trip',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '00273595-3d57-28a4-fdde-3d4d5dd34226',
  'type' => 'college',
  'language' => 'und',
  'created' => '1352367200',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'e5af6848-31d8-efc4-1dfb-3c356a1899be',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Vestibulum id ligula porta felis euismod semper. Curabitur blandit tempus porttitor. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Aenean eu leo quam...</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Vestibulum id ligula porta felis euismod semper. Curabitur blandit tempus porttitor. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Aenean eu leo quam...</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_custom_teaser_image' => array(
    'und' => array(
      0 => array(
        'fid' => '64',
        'alt' => '',
        'title' => '',
        'width' => '248',
        'height' => '258',
        'uid' => '1',
        'filename' => 'influencer_03.png',
        'uri' => 'public://influencer_03.png',
        'filemime' => 'image/png',
        'filesize' => '70927',
        'status' => '1',
        'timestamp' => '1352367200',
        'type' => 'image',
        'uuid' => '855904c1-fcf6-57f4-e983-ca8d508aa937',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_link_text' => array(
    'und' => array(
      0 => array(
        'value' => 'Go',
        'format' => NULL,
        'safe_value' => 'Go',
      ),
    ),
  ),
  'field_video' => array(
    'und' => array(
      0 => array(
        'fid' => '124',
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 16:33:20 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Go Trip',
  'log' => '',
  'status' => '1',
  'comment' => '2',
  'promote' => '1',
  'sticky' => '0',
  'vuuid' => '80f28d3b-e270-32d4-ed58-73689cbc84f3',
  'type' => 'webform',
  'language' => 'und',
  'created' => '1352359634',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'e5e6b1c4-e2d5-1cd4-f9f0-48cf9c92b7a2',
  'revision_uid' => '1',
  'body' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'webform' => array(
    'nid' => '47',
    'confirmation' => '',
    'confirmation_format' => NULL,
    'redirect_url' => '<confirmation>',
    'status' => '1',
    'block' => '0',
    'teaser' => '0',
    'allow_draft' => '0',
    'auto_save' => '0',
    'submit_notice' => '1',
    'submit_text' => '',
    'submit_limit' => '-1',
    'submit_interval' => '-1',
    'total_submit_limit' => '-1',
    'total_submit_interval' => '-1',
    'record_exists' => TRUE,
    'roles' => array(
      0 => '1',
      1 => '2',
    ),
    'emails' => array(),
    'components' => array(
      3 => array(
        'nid' => 47,
        'cid' => '3',
        'pid' => '0',
        'form_key' => 'full_name',
        'name' => 'Full Name',
        'type' => 'textfield',
        'value' => 'Full Name',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '2',
        'page_num' => 1,
      ),
      4 => array(
        'nid' => 47,
        'cid' => '4',
        'pid' => '0',
        'form_key' => 'contact_number',
        'name' => 'Contact Number',
        'type' => 'textfield',
        'value' => 'Contact Number',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '3',
        'page_num' => 1,
      ),
      5 => array(
        'nid' => 47,
        'cid' => '5',
        'pid' => '0',
        'form_key' => 'age',
        'name' => 'Age',
        'type' => 'textfield',
        'value' => 'Age',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'maxlength' => '3',
          'conditional_operator' => '=',
          'width' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '4',
        'page_num' => 1,
      ),
      1 => array(
        'nid' => 47,
        'cid' => '1',
        'pid' => '0',
        'form_key' => 'email',
        'name' => 'Email',
        'type' => 'email',
        'value' => 'Email',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '5',
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 47,
        'cid' => '2',
        'pid' => '0',
        'form_key' => 'nid',
        'name' => 'Nid',
        'type' => 'hidden',
        'value' => '',
        'extra' => array(
          'hidden_type' => 'hidden',
          'conditional_operator' => '=',
          'private' => 0,
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '6',
        'page_num' => 1,
      ),
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 14:27:14 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Bring',
  'log' => '',
  'status' => '1',
  'comment' => '2',
  'promote' => '1',
  'sticky' => '0',
  'vuuid' => 'd5b49d53-2fa3-1c04-3984-c642658b462d',
  'type' => 'webform',
  'language' => 'und',
  'created' => '1352359537',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'e8ca1be9-9795-e884-99ba-db2cb8a35ec1',
  'revision_uid' => '1',
  'body' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'webform' => array(
    'nid' => '30',
    'confirmation' => '',
    'confirmation_format' => 'filtered_html',
    'redirect_url' => '<confirmation>',
    'status' => '1',
    'block' => '1',
    'teaser' => '0',
    'allow_draft' => '0',
    'auto_save' => '0',
    'submit_notice' => '1',
    'submit_text' => 'Bring',
    'submit_limit' => '-1',
    'submit_interval' => '-1',
    'total_submit_limit' => '-1',
    'total_submit_interval' => '-1',
    'record_exists' => TRUE,
    'roles' => array(
      0 => '1',
      1 => '2',
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 30,
        'cid' => '1',
        'pid' => '0',
        'form_key' => 'email_to',
        'name' => 'To',
        'type' => 'email',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '0',
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 30,
        'cid' => '2',
        'pid' => '0',
        'form_key' => 'nid',
        'name' => 'Nid',
        'type' => 'hidden',
        'value' => '',
        'extra' => array(
          'hidden_type' => 'hidden',
          'conditional_operator' => '=',
          'private' => 0,
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '1',
        'page_num' => 1,
      ),
      3 => array(
        'nid' => 30,
        'cid' => '3',
        'pid' => '0',
        'form_key' => 'email_from',
        'name' => 'From',
        'type' => 'email',
        'value' => '',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '2',
        'page_num' => 1,
      ),
      4 => array(
        'nid' => 30,
        'cid' => '4',
        'pid' => '0',
        'form_key' => 'message',
        'name' => 'Message',
        'type' => 'textarea',
        'value' => '',
        'extra' => array(
          'title_display' => 0,
          'private' => 0,
          'resizable' => 0,
          'disabled' => 0,
          'conditional_operator' => '=',
          'cols' => '',
          'rows' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '3',
        'page_num' => 1,
      ),
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 14:25:37 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Give',
  'log' => '',
  'status' => '0',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'c29a470d-b83e-1af4-7936-a1be73ab5ba2',
  'type' => 'college',
  'language' => 'und',
  'created' => '1352367203',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'eeb6fbb4-e712-8c84-ddd1-18ec56268911',
  'revision_uid' => '1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Vestibulum id ligula porta felis euismod semper. Curabitur blandit tempus porttitor. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Aenean eu leo quam...</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => ' <p>Vestibulum id ligula porta felis euismod semper. Curabitur blandit tempus porttitor. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Aenean eu leo quam...</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_custom_teaser_image' => array(
    'und' => array(
      0 => array(
        'fid' => '65',
        'alt' => '',
        'title' => '',
        'width' => '248',
        'height' => '258',
        'uid' => '1',
        'filename' => 'influencer_03.png',
        'uri' => 'public://influencer_03_0.png',
        'filemime' => 'image/png',
        'filesize' => '70927',
        'status' => '1',
        'timestamp' => '1352367203',
        'type' => 'image',
        'uuid' => '27188aa6-19da-4904-b136-e7678002490c',
        'metatags' => array(),
        'rdf_mapping' => array(),
      ),
    ),
  ),
  'field_link_text' => array(
    'und' => array(
      0 => array(
        'value' => 'Give',
        'format' => NULL,
        'safe_value' => 'Give',
      ),
    ),
  ),
  'field_video' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-08 16:33:23 +0700',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Concierge',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '1',
  'sticky' => '0',
  'vuuid' => 'bd11d63f-7e13-fe34-c5c4-27abdd8bbaf3',
  'type' => 'webform',
  'language' => 'und',
  'created' => '1352192674',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => 'f3e53518-5b9b-4c04-054a-55e3d6707871',
  'revision_uid' => '1',
  'body' => array(),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'webform' => array(
    'nid' => '17',
    'confirmation' => '',
    'confirmation_format' => 'filtered_html',
    'redirect_url' => '<confirmation>',
    'status' => '1',
    'block' => '1',
    'teaser' => '0',
    'allow_draft' => '0',
    'auto_save' => '0',
    'submit_notice' => '1',
    'submit_text' => 'Reserve a seat',
    'submit_limit' => '-1',
    'submit_interval' => '-1',
    'total_submit_limit' => '-1',
    'total_submit_interval' => '-1',
    'record_exists' => TRUE,
    'roles' => array(
      0 => '1',
      1 => '2',
    ),
    'emails' => array(),
    'components' => array(
      1 => array(
        'nid' => 17,
        'cid' => '1',
        'pid' => '0',
        'form_key' => 'name',
        'name' => 'Name',
        'type' => 'textfield',
        'value' => 'Name',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '0',
        'page_num' => 1,
      ),
      2 => array(
        'nid' => 17,
        'cid' => '2',
        'pid' => '0',
        'form_key' => 'number',
        'name' => 'Number',
        'type' => 'textfield',
        'value' => 'Number',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'maxlength' => '',
          'field_prefix' => '',
          'field_suffix' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '0',
        'weight' => '1',
        'page_num' => 1,
      ),
      3 => array(
        'nid' => 17,
        'cid' => '3',
        'pid' => '0',
        'form_key' => 'email',
        'name' => 'Email',
        'type' => 'email',
        'value' => 'Email',
        'extra' => array(
          'title_display' => 'before',
          'private' => 0,
          'disabled' => 0,
          'unique' => 0,
          'conditional_operator' => '=',
          'width' => '',
          'description' => '',
          'attributes' => array(),
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '2',
        'page_num' => 1,
      ),
      4 => array(
        'nid' => 17,
        'cid' => '4',
        'pid' => '0',
        'form_key' => 'service',
        'name' => 'Service',
        'type' => 'select',
        'value' => 'service',
        'extra' => array(
          'items' => 'service|Service',
          'multiple' => 0,
          'title_display' => 'before',
          'private' => 0,
          'aslist' => 1,
          'optrand' => 0,
          'conditional_operator' => '=',
          'other_option' => NULL,
          'other_text' => 'Other...',
          'description' => '',
          'custom_keys' => FALSE,
          'options_source' => '',
          'conditional_component' => '',
          'conditional_values' => '',
        ),
        'mandatory' => '1',
        'weight' => '3',
        'page_num' => 1,
      ),
    ),
  ),
  'machine_name' => FALSE,
  'name' => 'admin',
  'picture' => '145',
  'data' => 'a:8:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_popup";s:1:"f";s:13:"ckeditor_skin";s:4:"kama";s:15:"ckeditor_expand";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2012-11-06 16:04:34 +0700',
);
  return $nodes;
}
